[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pcredz"
version = "1.0"
requires-python = ">=3.9"
dependencies = [
    "cython",
    "python-libpcap",
]

[project.scripts]
pcredz = "pcredz:main"